/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogPilihPembeli.java
 *
 * Created on Nov 12, 2011, 1:13:30 PM
 */
package com.prima.view.barang;

import com.prima.dao.BarangDAO;
import com.prima.entity.Barang;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raphael
 */
public class DialogPilihBarang extends javax.swing.JDialog {

    private String[] header = {"ID Barang", "nama", "harga IDR","Harga USD", "stock", "satuan jual", "command"};
    private DefaultTableModel modelBarang = new DefaultTableModel(null, header);
    private static Barang selectedBarang = null;

    /** Creates new form DialogPilihPembeli */
    public DialogPilihBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        jtfCari.getDocument().addDocumentListener(new PembeliSearchListener());
        jtblBarang.setModel(modelBarang);
        jtblBarang.setRowHeight(30);
        jtblBarang.setAutoCreateRowSorter(true);
        refreshData(new BarangDAO().getAllBarang());
        selectedBarang = null;
        this.setLocationRelativeTo(null);
    }

    private void refreshData(List<Barang> listBarang) {
        NumberFormat formatID = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        NumberFormat formatUS = NumberFormat.getCurrencyInstance(Locale.US);
        removeTableModel(modelBarang);
        String satuanJual = "";

        for (Barang b : listBarang) {
            if (b.getSatuanJual()) {
                satuanJual = "Kg";
            } else {
                satuanJual = "Liter";
            }
            if (b.getStock()>0) {
                modelBarang.addRow(new Object[]{b.getIdBarang(), b.getNama(), formatID.format(b.getHargaIdr()),formatUS.format(b.getHargaUsd()), b.getStock(), satuanJual, b.getIdBarang()});
            }
  
        }
    }

    private void removeTableModel(DefaultTableModel model) {
        int row = model.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
    }

    public static Barang getSelectedBarang() {
        return selectedBarang;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblBarang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtfCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pilih Barang");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jtblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblBarang);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jtfCari, gridBagConstraints);

        jLabel1.setText("Cari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        int idBarang = (Integer) jtblBarang.getValueAt(jtblBarang.getSelectedRow(), 0);
        selectedBarang = new BarangDAO().getBarangById(idBarang);
        this.setVisible(false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Pilih pembeli terlebih dahulu!");
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jtblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblBarangMouseClicked
    try {
        if (evt.getClickCount() == 2) {
            int idBarang = (Integer) jtblBarang.getValueAt(jtblBarang.getSelectedRow(), 0);
            selectedBarang = new BarangDAO().getBarangById(idBarang);
            this.setVisible(false);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Pilih pembeli terlebih dahulu!");
    }

}//GEN-LAST:event_jtblBarangMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblBarang;
    private javax.swing.JTextField jtfCari;
    // End of variables declaration//GEN-END:variables

    class PembeliSearchListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            refreshData(new BarangDAO().searchBarang(jtfCari.getText()));
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            refreshData(new BarangDAO().searchBarang(jtfCari.getText()));
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            refreshData(new BarangDAO().searchBarang(jtfCari.getText()));
        }
    }
}
