/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogUbahBarang.java
 *
 * Created on Sep 28, 2011, 5:56:25 PM
 */
package com.prima.view.barang;

import com.prima.dao.BarangDAO;
import com.prima.entity.Barang;
import javax.swing.JOptionPane;

/**
 *
 * @author raphael
 */
public class DialogUbahBarang extends javax.swing.JDialog {

    /** Creates new form DialogUbahBarang */
    //private Barang barang=null;
    private int id;
    private double stock;

    public DialogUbahBarang(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        initData(id);
    }

    private void initData(int id) {
        BarangDAO dao = new BarangDAO();
        Barang barang = dao.getBarangById(id);
        this.id = id;
        stock = barang.getStock();
        jtfNamaBarang.setText(barang.getNama());
        jtfHarga.setText(barang.getHargaIdr() + "");
        jtfHargaUSD.setText(barang.getHargaUsd()+"");
        if (!barang.getSatuanJual()) {
            jrbLiter.setSelected(true);
        } else {
            jrbKg.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNamaBarang = new javax.swing.JTextField();
        jrbLiter = new javax.swing.JRadioButton();
        jrbKg = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtfHarga = new com.prima.view.model.NumberTextbox();
        jLabel4 = new javax.swing.JLabel();
        jtfHargaUSD = new com.prima.view.model.NumberTextbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ubah Barang");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nama Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Harga IDR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Satuan Jual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jtfNamaBarang, gridBagConstraints);

        buttonGroup1.add(jrbLiter);
        jrbLiter.setSelected(true);
        jrbLiter.setText("Liter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jrbLiter, gridBagConstraints);

        buttonGroup1.add(jrbKg);
        jrbKg.setText("Kg");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jrbKg, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jtfHarga, gridBagConstraints);

        jLabel4.setText("Harga USD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jtfHargaUSD, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //barang.setIdBarang(1);
    if (jtfNamaBarang.getText().trim().equals("") || jtfHarga.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Data barang belum lengkap");
    } else {
        Barang brg = new Barang();
        brg.setIdBarang(id);
        brg.setNama(jtfNamaBarang.getText());
        brg.setHargaIdr(Double.parseDouble(jtfHarga.getText()));
        brg.setHargaUsd(Double.parseDouble(jtfHargaUSD.getText()));
        brg.setSatuanJual(jrbKg.isSelected());
        brg.setStock(stock);
        
        new BarangDAO().updateBarang(brg);
        this.setVisible(false);
    }

}//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbKg;
    private javax.swing.JRadioButton jrbLiter;
    private com.prima.view.model.NumberTextbox jtfHarga;
    private com.prima.view.model.NumberTextbox jtfHargaUSD;
    private javax.swing.JTextField jtfNamaBarang;
    // End of variables declaration//GEN-END:variables
}
