package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Barang generated by hbm2java
 */
public class Barang implements java.io.Serializable {

    private Integer idBarang;
    private String nama;
    private Double stock;
    private Double hargaIdr;
    private double hargaUsd;
    private Boolean satuanJual;
    private Set pembelianDetails = new HashSet(0);
    private Set detailTransaksis = new HashSet(0);

    public Barang() {
    }

    public Barang(double hargaUsd) {
        this.hargaUsd = hargaUsd;
    }

    public Barang(String nama, Double stock, Double hargaIdr, double hargaUsd, Boolean satuanJual, Set pembelianDetails, Set detailTransaksis) {
        this.nama = nama;
        this.stock = stock;
        this.hargaIdr = hargaIdr;
        this.hargaUsd = hargaUsd;
        this.satuanJual = satuanJual;
        this.pembelianDetails = pembelianDetails;
        this.detailTransaksis = detailTransaksis;
    }

    public Integer getIdBarang() {
        return this.idBarang;
    }

    public void setIdBarang(Integer idBarang) {
        this.idBarang = idBarang;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public Double getStock() {
        return this.stock;
    }

    public void setStock(Double stock) {
        this.stock = stock;
    }

    public Double getHargaIdr() {
        return this.hargaIdr;
    }

    public void setHargaIdr(Double hargaIdr) {
        this.hargaIdr = hargaIdr;
    }

    public double getHargaUsd() {
        return this.hargaUsd;
    }

    public void setHargaUsd(double hargaUsd) {
        this.hargaUsd = hargaUsd;
    }

    public Boolean getSatuanJual() {
        return this.satuanJual;
    }

    public void setSatuanJual(Boolean satuanJual) {
        this.satuanJual = satuanJual;
    }

    public Set getPembelianDetails() {
        return this.pembelianDetails;
    }

    public void setPembelianDetails(Set pembelianDetails) {
        this.pembelianDetails = pembelianDetails;
    }

    public Set getDetailTransaksis() {
        return this.detailTransaksis;
    }

    public void setDetailTransaksis(Set detailTransaksis) {
        this.detailTransaksis = detailTransaksis;
    }

    public String toString() {
        return this.nama;
    }
}
