package com.prima.entity;
// Generated Apr 29, 2012 9:01:21 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cicilan generated by hbm2java
 */
public class Cicilan  implements java.io.Serializable {


     private Integer idCicilan;
     private Kredit kredit;
     private Double jumlahBayar;
     private Date tglCicilan;
     private String jenis;
     private String noGiro;

    public Cicilan() {
    }

	
    public Cicilan(String jenis, String noGiro) {
        this.jenis = jenis;
        this.noGiro = noGiro;
    }
    public Cicilan(Kredit kredit, Double jumlahBayar, Date tglCicilan, String jenis, String noGiro) {
       this.kredit = kredit;
       this.jumlahBayar = jumlahBayar;
       this.tglCicilan = tglCicilan;
       this.jenis = jenis;
       this.noGiro = noGiro;
    }
   
    public Integer getIdCicilan() {
        return this.idCicilan;
    }
    
    public void setIdCicilan(Integer idCicilan) {
        this.idCicilan = idCicilan;
    }
    public Kredit getKredit() {
        return this.kredit;
    }
    
    public void setKredit(Kredit kredit) {
        this.kredit = kredit;
    }
    public Double getJumlahBayar() {
        return this.jumlahBayar;
    }
    
    public void setJumlahBayar(Double jumlahBayar) {
        this.jumlahBayar = jumlahBayar;
    }
    public Date getTglCicilan() {
        return this.tglCicilan;
    }
    
    public void setTglCicilan(Date tglCicilan) {
        this.tglCicilan = tglCicilan;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public String getNoGiro() {
        return this.noGiro;
    }
    
    public void setNoGiro(String noGiro) {
        this.noGiro = noGiro;
    }




}


