package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA



/**
 * DetailTransaksi generated by hbm2java
 */
public class DetailTransaksi  implements java.io.Serializable {


     private String idDetailTransaksi;
     private Transaksi transaksi;
     private Barang barang;
     private Double jumlah;
     private Double harga;
     private Boolean mataUang;

    public DetailTransaksi() {
    }

	
    public DetailTransaksi(String idDetailTransaksi) {
        this.idDetailTransaksi = idDetailTransaksi;
    }
    public DetailTransaksi(String idDetailTransaksi, Transaksi transaksi, Barang barang, Double jumlah, Double harga, Boolean mataUang) {
       this.idDetailTransaksi = idDetailTransaksi;
       this.transaksi = transaksi;
       this.barang = barang;
       this.jumlah = jumlah;
       this.harga = harga;
       this.mataUang = mataUang;
    }
   
    public String getIdDetailTransaksi() {
        return this.idDetailTransaksi;
    }
    
    public void setIdDetailTransaksi(String idDetailTransaksi) {
        this.idDetailTransaksi = idDetailTransaksi;
    }
    public Transaksi getTransaksi() {
        return this.transaksi;
    }
    
    public void setTransaksi(Transaksi transaksi) {
        this.transaksi = transaksi;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public Double getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Double jumlah) {
        this.jumlah = jumlah;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public Boolean getMataUang() {
        return this.mataUang;
    }
    
    public void setMataUang(Boolean mataUang) {
        this.mataUang = mataUang;
    }




}


