package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kredit generated by hbm2java
 */
public class Kredit  implements java.io.Serializable {


     private Integer idKredit;
     private Transaksi transaksi;
     private Date tglAkhirPelunasan;
     private Boolean status;
     private Set cicilans = new HashSet(0);

    public Kredit() {
    }

    public Kredit(Transaksi transaksi, Date tglAkhirPelunasan, Boolean status, Set cicilans) {
       this.transaksi = transaksi;
       this.tglAkhirPelunasan = tglAkhirPelunasan;
       this.status = status;
       this.cicilans = cicilans;
    }
   
    public Integer getIdKredit() {
        return this.idKredit;
    }
    
    public void setIdKredit(Integer idKredit) {
        this.idKredit = idKredit;
    }
    public Transaksi getTransaksi() {
        return this.transaksi;
    }
    
    public void setTransaksi(Transaksi transaksi) {
        this.transaksi = transaksi;
    }
    public Date getTglAkhirPelunasan() {
        return this.tglAkhirPelunasan;
    }
    
    public void setTglAkhirPelunasan(Date tglAkhirPelunasan) {
        this.tglAkhirPelunasan = tglAkhirPelunasan;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCicilans() {
        return this.cicilans;
    }
    
    public void setCicilans(Set cicilans) {
        this.cicilans = cicilans;
    }




}


