package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Pembeli generated by hbm2java
 */
public class Pembeli implements java.io.Serializable {

    private Integer idPembeli;
    private String nama;
    private String alamat;
    private String telp;
    private String email;
    private Set transaksis = new HashSet(0);

    public Pembeli() {
    }

    public Pembeli(String nama, String alamat, String telp, String email, Set transaksis) {
        this.nama = nama;
        this.alamat = alamat;
        this.telp = telp;
        this.email = email;
        this.transaksis = transaksis;
    }

    public Integer getIdPembeli() {
        return this.idPembeli;
    }

    public void setIdPembeli(Integer idPembeli) {
        this.idPembeli = idPembeli;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getAlamat() {
        return this.alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    public String getTelp() {
        return this.telp;
    }

    public void setTelp(String telp) {
        this.telp = telp;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getTransaksis() {
        return this.transaksis;
    }

    public void setTransaksis(Set transaksis) {
        this.transaksis = transaksis;
    }

    public String toString() {
        return this.nama;
    }
}
