package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA



/**
 * PembelianDetail generated by hbm2java
 */
public class PembelianDetail  implements java.io.Serializable {


     private String idPembelianDetail;
     private Barang barang;
     private Pembelian pembelian;
     private Integer jumlah;
     private Double harga;
     private Boolean mataUang;

    public PembelianDetail() {
    }

	
    public PembelianDetail(String idPembelianDetail) {
        this.idPembelianDetail = idPembelianDetail;
    }
    public PembelianDetail(String idPembelianDetail, Barang barang, Pembelian pembelian, Integer jumlah, Double harga, Boolean mataUang) {
       this.idPembelianDetail = idPembelianDetail;
       this.barang = barang;
       this.pembelian = pembelian;
       this.jumlah = jumlah;
       this.harga = harga;
       this.mataUang = mataUang;
    }
   
    public String getIdPembelianDetail() {
        return this.idPembelianDetail;
    }
    
    public void setIdPembelianDetail(String idPembelianDetail) {
        this.idPembelianDetail = idPembelianDetail;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public Pembelian getPembelian() {
        return this.pembelian;
    }
    
    public void setPembelian(Pembelian pembelian) {
        this.pembelian = pembelian;
    }
    public Integer getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Integer jumlah) {
        this.jumlah = jumlah;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public Boolean getMataUang() {
        return this.mataUang;
    }
    
    public void setMataUang(Boolean mataUang) {
        this.mataUang = mataUang;
    }




}


