package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pembelian generated by hbm2java
 */
public class Pembelian implements java.io.Serializable, Comparable<Pembelian> {

    private String idPembelian;
    private Supplier supplier;
    private Date tglBeli;
    private Integer kurs;
    private Integer hargaTotal;
    private Boolean status;
    private Set pembelianDetails = new HashSet(0);

    public Pembelian() {
    }

    public Pembelian(String idPembelian) {
        this.idPembelian = idPembelian;
    }

    public Pembelian(String idPembelian, Supplier supplier, Date tglBeli, Integer kurs, Integer hargaTotal, Boolean status, Set pembelianDetails) {
        this.idPembelian = idPembelian;
        this.supplier = supplier;
        this.tglBeli = tglBeli;
        this.kurs = kurs;
        this.hargaTotal = hargaTotal;
        this.status = status;
        this.pembelianDetails = pembelianDetails;
    }

    public String getIdPembelian() {
        return this.idPembelian;
    }

    public void setIdPembelian(String idPembelian) {
        this.idPembelian = idPembelian;
    }

    public Supplier getSupplier() {
        return this.supplier;
    }

    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    public Date getTglBeli() {
        return this.tglBeli;
    }

    public void setTglBeli(Date tglBeli) {
        this.tglBeli = tglBeli;
    }

    public Integer getKurs() {
        return this.kurs;
    }

    public void setKurs(Integer kurs) {
        this.kurs = kurs;
    }

    public Integer getHargaTotal() {
        return this.hargaTotal;
    }

    public void setHargaTotal(Integer hargaTotal) {
        this.hargaTotal = hargaTotal;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Set getPembelianDetails() {
        return this.pembelianDetails;
    }

    public void setPembelianDetails(Set pembelianDetails) {
        this.pembelianDetails = pembelianDetails;
    }

    @Override
    public int compareTo(Pembelian o) {
        return o.getTglBeli().compareTo(this.tglBeli);
    }
}
