package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA



/**
 * Pengguna generated by hbm2java
 */
public class Pengguna  implements java.io.Serializable {


     private String namaPengguna;
     private String password;
     private short role;

    public Pengguna() {
    }

	
    public Pengguna(String namaPengguna, short role) {
        this.namaPengguna = namaPengguna;
        this.role = role;
    }
    public Pengguna(String namaPengguna, String password, short role) {
       this.namaPengguna = namaPengguna;
       this.password = password;
       this.role = role;
    }
   
    public String getNamaPengguna() {
        return this.namaPengguna;
    }
    
    public void setNamaPengguna(String namaPengguna) {
        this.namaPengguna = namaPengguna;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public short getRole() {
        return this.role;
    }
    
    public void setRole(short role) {
        this.role = role;
    }




}


