package com.prima.entity;
// Generated Apr 16, 2012 3:04:35 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

    private Integer idSupplier;
    private String nama;
    private String alamat;
    private String telp;
    private String email;
    private Set pembelians = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String nama, String alamat, String telp, String email, Set pembelians) {
        this.nama = nama;
        this.alamat = alamat;
        this.telp = telp;
        this.email = email;
        this.pembelians = pembelians;
    }

    public Integer getIdSupplier() {
        return this.idSupplier;
    }

    public void setIdSupplier(Integer idSupplier) {
        this.idSupplier = idSupplier;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getAlamat() {
        return this.alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    public String getTelp() {
        return this.telp;
    }

    public void setTelp(String telp) {
        this.telp = telp;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getPembelians() {
        return this.pembelians;
    }

    public void setPembelians(Set pembelians) {
        this.pembelians = pembelians;
    }

    public String toString() {
        return this.nama;
    }
}
