/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelLaporanStockBarang.java
 *
 * Created on Oct 23, 2011, 8:00:47 PM
 */
package com.prima.view.laporan;

import com.prima.dao.BarangDAO;
import com.prima.entity.Barang;
import static net.sf.dynamicreports.report.builder.DynamicReports.*;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import net.sf.dynamicreports.examples.DataSource;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.style.ConditionalStyleBuilder;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author raphael
 */
public class PanelLaporanStockBarang extends javax.swing.JPanel {

    /** Creates new form PanelLaporanStockBarang */
    public PanelLaporanStockBarang() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public JasperPrint createReport() throws Exception {
        if (jdcBarang.getDate() == null) {
            throw new Exception("Tanggal Harus diisi!");
        }
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        StyleBuilder boldStyle = stl.style().bold();
        StyleBuilder boldCenteredStyle = stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.CENTER);
        StyleBuilder TitleStyle = stl.style(boldStyle).setFontSize(20);
        StyleBuilder columnTitleStyle = stl.style(boldCenteredStyle).setBorder(stl.pen1Point()).setBackgroundColor(Color.LIGHT_GRAY);

        //                                                           title,     field name     data type
        TextColumnBuilder<Integer> itemColumn = col.column("ID Barang", "item", type.integerType());
        TextColumnBuilder<String> quantityColumn = col.column("Nama Barang", "quantity", type.stringType());
        TextColumnBuilder<Double> unitPriceColumn = col.column("Stock Barang", "unitprice", type.doubleType());
         TextColumnBuilder<String> satuanColumn = col.column("Satuan Jual", "satuan", type.stringType());

        TextColumnBuilder<Integer> rowNumberColumn = col.reportRowNumberColumn("No.") //sets the fixed width of a column, width = 2 * character width
                .setFixedColumns(2).setHorizontalAlignment(HorizontalAlignment.CENTER);
        ConditionalStyleBuilder condition1 = stl.conditionalStyle(cnd.smallerOrEquals(unitPriceColumn, 5)).setBackgroundColor(Color.yellow);
        JasperPrint jPrint = null;
        try {
            jPrint = report()//create new report design
                    .setColumnTitleStyle(columnTitleStyle).highlightDetailEvenRows().columns(//add columns
                    rowNumberColumn, itemColumn, quantityColumn, unitPriceColumn,satuanColumn).title(cmp.verticalList().add(
                    cmp.text("PD.Prima").setStyle(TitleStyle),
                    cmp.text("Kartu Stock Barang").setStyle(stl.style().setFontSize(18)).setHorizontalAlignment(HorizontalAlignment.LEFT)
                    ),
                    cmp.text("Tanggal cetak "+format.format(new Date()))).detailRowHighlighters(condition1)//shows report title
                    .pageFooter(cmp.pageXofY().setStyle(boldCenteredStyle))//shows number of page at page footer
                    .setDataSource(createDataSource())//set datasource
                    .toJasperPrint();
        } catch (DRException e) {
            e.printStackTrace();
        }
        return jPrint;
    }

    private JRDataSource createDataSource() {
        BarangDAO barangDAO = new BarangDAO();
        List<Barang> list = barangDAO.getAllBarang();
        DataSource dataSource = new DataSource("item", "quantity", "unitprice","satuan");
        for (Barang barang : list) {
            String satuanJual="Liter";
            if (barang.getSatuanJual()) {
                satuanJual="Kg";
            }
            dataSource.add(barang.getIdBarang(), barang.getNama(), barangDAO.getTotalBarang(barang, jdcBarang.getDate()),satuanJual);
        }

        return dataSource;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jdcBarang = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jdcBarang.setDateFormatString("dd/MM/yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jdcBarang, gridBagConstraints);

        jLabel1.setText("Tanggal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcBarang;
    // End of variables declaration//GEN-END:variables
//    class LaporanStockBarangService {
//        public JRDataSource getDataSource(){
//            DataSource dataSource= new DataSource(columns)
//            return null;
//        }
//    }
}
