/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelLaporanStockBarang.java
 *
 * Created on Oct 23, 2011, 8:00:47 PM
 */
package com.prima.view.laporan;

import com.prima.dao.PembelianDAO;
import com.prima.dao.TransaksiDAO;
import static net.sf.dynamicreports.report.builder.DynamicReports.*;
import java.awt.Color;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import net.sf.dynamicreports.examples.DataSource;
import net.sf.dynamicreports.report.builder.column.TextColumnBuilder;
import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author raphael
 */
public class PanelLaporanLabaRugi extends javax.swing.JPanel {

    /** Creates new form PanelLaporanStockBarang */
    public PanelLaporanLabaRugi() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public JasperPrint createReport() {
NumberFormat formatIDR = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        PembelianDAO pembelianDAO = new PembelianDAO();
        TransaksiDAO transaksiDAO = new TransaksiDAO();
        int totalPembelian = pembelianDAO.getTotalPembelian(jmcMonth.getMonth(), jycYear.getYear());
        int totalTransaksi = transaksiDAO.getTotalTransaksi(jmcMonth.getMonth(), jycYear.getYear());
        int saldo = totalTransaksi - totalPembelian;

        String[] months = new DateFormatSymbols(new Locale("in", "ID")).getMonths();

        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        StyleBuilder boldStyle = stl.style().bold();
        StyleBuilder boldCenteredStyle = stl.style(boldStyle).setHorizontalAlignment(HorizontalAlignment.CENTER);
        StyleBuilder TitleStyle = stl.style(boldStyle).setFontSize(20);
        StyleBuilder columnTitleStyle = stl.style().setHorizontalAlignment(HorizontalAlignment.CENTER).setBorder(stl.pen1Point()).setBackgroundColor(Color.LIGHT_GRAY);

        //                                                           title,     field name     data type
        TextColumnBuilder<String> idColumn = col.column("ID Transaksi", "id", type.stringType());
        TextColumnBuilder<String> nameColumn = col.column("Nama Pembeli/Supplier", "nama", type.stringType());
        TextColumnBuilder<Date> dateColumn = col.column("Tanggal", "tanggal", type.dateYearToMinuteType());
        TextColumnBuilder<String> buyColumn = col.column("Debet", "beli", type.stringType()).setHorizontalAlignment(HorizontalAlignment.CENTER);
        TextColumnBuilder<String> sellColumn = col.column("Kredit", "jual", type.stringType()).setHorizontalAlignment(HorizontalAlignment.CENTER);
        TextColumnBuilder<String> saldoColumn = col.column("Saldo", "saldo", type.stringType()).setHorizontalAlignment(HorizontalAlignment.CENTER);

        TextColumnBuilder<Integer> rowNumberColumn = col.reportRowNumberColumn("No.") //sets the fixed width of a column, width = 2 * character width
                .setFixedColumns(2).setHorizontalAlignment(HorizontalAlignment.CENTER);
        //ConditionalStyleBuilder condition1 = stl.conditionalStyle(cnd.smallerOrEquals(buyColumn, 5)).setBackgroundColor(Color.yellow);
        JasperPrint jPrint = null;
        try {
            jPrint = report()//create new report design
                    .setColumnTitleStyle(columnTitleStyle).highlightDetailEvenRows().columns(//add columns
                    rowNumberColumn, idColumn, nameColumn, dateColumn, buyColumn, sellColumn, saldoColumn).title(cmp.verticalList().add(
                    cmp.text("PD.Prima").setStyle(TitleStyle),
                    cmp.text("Laporan Laba Rugi Bulan " + months[jmcMonth.getMonth()] + " " + jycYear.getYear()).setStyle(stl.style().setFontSize(18)).setHorizontalAlignment(HorizontalAlignment.LEFT)),
                    cmp.text("tanggal cetak "+format.format(new Date())),
                    cmp.text("Saldo awal "+formatIDR.format(saldo))).pageFooter(cmp.pageXofY().setStyle(boldCenteredStyle))//shows number of page at page footer
                    .setDataSource(createDataSource())//set datasource
                    .toJasperPrint();
        } catch (DRException e) {
            e.printStackTrace();
        }
        return jPrint;
    }
////

    private JRDataSource createDataSource() {

        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        DataSource dataSource = new DataSource("id", "nama", "tanggal", "beli", "jual", "saldo");
        PembelianDAO pembelianDAO = new PembelianDAO();
        TransaksiDAO transaksiDAO = new TransaksiDAO();
        int totalPembelian = pembelianDAO.getTotalPembelian(jmcMonth.getMonth(), jycYear.getYear());
        int totalTransaksi = transaksiDAO.getTotalTransaksi(jmcMonth.getMonth(), jycYear.getYear());
        int saldo = totalTransaksi - totalPembelian;
        List<Object> list = transaksiDAO.getDetailTransaksi(jmcMonth.getMonth(), jycYear.getYear());

        for (Object object : list) {
            Object[] temp = (Object[]) object;
            saldo -= Integer.parseInt(temp[3].toString());
            saldo += Integer.parseInt(temp[4].toString());
            dataSource.add(temp[0].toString(), temp[2], temp[1], format.format(temp[3]), format.format(temp[4]), format.format(saldo));
        }
        return dataSource;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmcMonth = new com.toedter.calendar.JMonthChooser();
        jLabel4 = new javax.swing.JLabel();
        jycYear = new com.toedter.calendar.JYearChooser();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Bulan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jmcMonth, gridBagConstraints);

        jLabel4.setText("Tahun");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jycYear, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JMonthChooser jmcMonth;
    private com.toedter.calendar.JYearChooser jycYear;
    // End of variables declaration//GEN-END:variables
}
