/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelLaporanPenjualanGlobal.java
 *
 * Created on Oct 24, 2011, 2:12:57 PM
 */
package com.prima.view.laporan;

import com.prima.service.ReportService2;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author raphael
 */
public class PanelLaporanPenjualanGlobal extends javax.swing.JPanel {

    /** Creates new form PanelLaporanPenjualanGlobal */
    public PanelLaporanPenjualanGlobal() {
        initComponents();
    }

    public JasperPrint createReport() throws Exception {
        if (jdcTglAwal.getDate() == null && jdcTglAkhir.getDate() == null) {
            throw new Exception("Tanggal Harus diisi!");
        } else if (jdcTglAwal.getDate().after(jdcTglAkhir.getDate())) {
            throw new Exception("Pengisian tanggal salah");
        } else {
            HashMap<Object, Object> param = new HashMap<Object, Object>();
            param.put("tglAwal", jdcTglAwal.getDate());
            param.put("tglAkhir", jdcTglAkhir.getDate());
            ReportService2 reportService2 = new ReportService2("report//reportPenjualanGlobal.jrxml", param);
            return reportService2.getReport();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jdcTglAkhir = new com.toedter.calendar.JDateChooser();
        jdcTglAwal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jdcTglAkhir.setDateFormatString("dd/MM/yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jdcTglAkhir, gridBagConstraints);

        jdcTglAwal.setDateFormatString("dd/MM/yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jdcTglAwal, gridBagConstraints);

        jLabel1.setText("Tanggal Akhir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Tanggal Awal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(jLabel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jdcTglAkhir;
    private com.toedter.calendar.JDateChooser jdcTglAwal;
    // End of variables declaration//GEN-END:variables
}
