/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBarang.java
 *
 * Created on Sep 23, 2011, 4:50:15 PM
 */
package com.prima.view.pembeli;

import com.prima.dao.PembeliDAO;
import com.prima.dao.TransaksiDAO;
import com.prima.entity.Kredit;
import com.prima.entity.Pembeli;
import com.prima.entity.Transaksi;
import com.prima.view.model.ButtonEditor;
import com.prima.view.model.ButtonRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.swing.JCheckBox;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raphael
 */
public class PanelPembeli extends javax.swing.JPanel {

    private String[] header = {"ID Pembeli", "Nama", "Alamat", "Telp", "Fax", "command"};
    private DefaultTableModel modelPembeli = new DefaultTableModel(null, header);
    private DefaultTableModel modelTransaksi = new DefaultTableModel(null, new Object[]{"ID Transaksi", "Tanggal Jual", "Kurs", "Harga Total", "Jenis Pembayaran", "Status Pembayaran"});
    private ButtonEditor btnEditor = new ButtonEditor(new JCheckBox());

    /** Creates new form PanelBarang */
    public PanelPembeli() {
        initComponents();
        init();
        refreshData(new PembeliDAO().getAllPembeli());
    }

    private void init() {
        jtfSearch.getDocument().addDocumentListener(new DocumentListenerSearchBarang());
        jtblPembeli.setAutoCreateRowSorter(true);
        jtblPembeli.setRowHeight(25);
        jtblPembeli.setModel(modelPembeli);
        jtblPembeli.getColumn("command").setCellRenderer(new ButtonRenderer());
        btnEditor.getButton().addActionListener(new ButtonEditorListener());
        jtblPembeli.getColumn("command").setCellEditor(btnEditor);
        jtblPembeli.getSelectionModel().addListSelectionListener(new PembeliListSelectionListener());

        jtblTransaksi.setModel(modelTransaksi);
        jtblTransaksi.setAutoCreateRowSorter(true);
        jtblPembeli.setAutoCreateRowSorter(true);
    }

    private void refreshData(List<Pembeli> listBarang) {
        removeTableModel(modelPembeli);
        for (Pembeli b : listBarang) {
            modelPembeli.addRow(new Object[]{b.getIdPembeli(), b.getNama(), b.getAlamat(), b.getTelp(), b.getEmail(), b.getIdPembeli()});
        }
    }

    private void removeTableModel(DefaultTableModel model) {
        int row = model.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
    }

    private void refreshTableTransaksi(List<Transaksi> dataTransaksi) {
         NumberFormat formatIDR = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
        NumberFormat formatUSD = NumberFormat.getCurrencyInstance(Locale.US);
        removeTableModel(modelTransaksi);
        for (Transaksi transaksi : dataTransaksi) {
            String jenisTransaksi = "Tunai";
            String statusPembayaran = "Lunas";
            if (!transaksi.getKredits().isEmpty()) {
                jenisTransaksi = "Kredit";
                Iterator<Kredit> it = transaksi.getKredits().iterator();
                while (it.hasNext()) {
                    Kredit k = it.next();
                    if (!k.getStatus()) {
                        statusPembayaran = "Belum Lunas";
                    }
                }
            }
            if (transaksi.isMata()) {
                modelTransaksi.addRow(new Object[]{transaksi.getIdTransaksi(), transaksi.getTglJual(), transaksi.getKurs(), formatIDR.format(transaksi.getHargaTotal()), jenisTransaksi, statusPembayaran, transaksi.getIdTransaksi(), transaksi.getStatus()});
            }else{
                modelTransaksi.addRow(new Object[]{transaksi.getIdTransaksi(), transaksi.getTglJual(), transaksi.getKurs(), formatUSD.format(transaksi.getHargaTotalUsd()), jenisTransaksi, statusPembayaran, transaksi.getIdTransaksi(), transaksi.getStatus()});
            }
            
        }
    }

    public void refresh() {
        PembeliDAO dao = new PembeliDAO();
        refreshData(dao.getAllPembeli());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPembeli = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTransaksi = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel1.setText("Cari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 18);
        add(jtfSearch, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jButton2, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembeli"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtblPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPembeli);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi Penjualan"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblTransaksi);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    DialogTambahPembeli d = new DialogTambahPembeli(null, true);
    d.setVisible(true);
    refreshData(new PembeliDAO().getAllPembeli());
}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblPembeli;
    private javax.swing.JTable jtblTransaksi;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables

    class PembeliListSelectionListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            try {
                Pembeli p = new PembeliDAO().getPembeliById(Integer.parseInt(jtblPembeli.getValueAt(jtblPembeli.getSelectedRow(), 0) + ""));
                refreshTableTransaksi(new TransaksiDAO().getTransaksiByPembeli(p));
            } catch (Exception ex) {
                //ex.printStackTrace();
            }

        }
    }

    class ButtonEditorListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            DialogUbahPembeli dialog = new DialogUbahPembeli(null, true, Integer.parseInt(btnEditor.getCellEditorValue().toString()));
            dialog.setVisible(true);
            refreshData(new PembeliDAO().getAllPembeli());
        }
    }

    class DocumentListenerSearchBarang implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            refreshData(new PembeliDAO().searchPembeli(jtfSearch.getText()));
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            refreshData(new PembeliDAO().searchPembeli(jtfSearch.getText()));
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            refreshData(new PembeliDAO().searchPembeli(jtfSearch.getText()));
        }
    }
}
