/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelBarang.java
 *
 * Created on Sep 23, 2011, 4:50:15 PM
 */
package com.prima.view.supplier;

import com.prima.dao.SupplierDAO;
import com.prima.entity.Pembelian;
import com.prima.entity.Supplier;
import com.prima.view.model.ButtonEditor;
import com.prima.view.model.ButtonRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.swing.JCheckBox;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raphael
 */
public class PanelSupplier extends javax.swing.JPanel {

    private String[] header = {"ID Supplier", "Nama", "Alamat", "Telp", "Fax", "command"};
    private DefaultTableModel tableModel = new DefaultTableModel(null, header);
    private DefaultTableModel tableModelPembelian = new DefaultTableModel(null, new Object[]{"id", "tanggal", "kurs", "total"});
    // private DialogUbahBarang dialog;
    private ButtonEditor btnEditor = new ButtonEditor(new JCheckBox());

    /** Creates new form PanelBarang */
    public PanelSupplier() {
        initComponents();
        init();
        refreshData(new SupplierDAO().getAllSupplier());
    }

    private void init() {
        jtfSearch.getDocument().addDocumentListener(new DocumentListenerSearchSupplier());
        jtblSupplier.setAutoCreateRowSorter(true);
        jtblSupplier.setRowHeight(25);
        jtblSupplier.setModel(tableModel);
        jtblSupplier.getColumn("command").setCellRenderer(new ButtonRenderer());
        jtblSupplier.getSelectionModel().addListSelectionListener(new PembelianSelectionListener());
        btnEditor.getButton().addActionListener(new ButtonEditorListener());
        jtblSupplier.getColumn("command").setCellEditor(btnEditor);

        jtblPembelian.setModel(tableModelPembelian);
        jtblPembelian.setAutoCreateRowSorter(true);
        jtblSupplier.setAutoCreateRowSorter(true);
    }

    private void refreshData(List<Supplier> listSupplier) {
        int row = tableModel.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModel.removeRow(0);
        }
        for (Supplier b : listSupplier) {
            tableModel.addRow(new Object[]{b.getIdSupplier(), b.getNama(), b.getAlamat(), b.getTelp(), b.getEmail(), b.getIdSupplier()});
        }
    }

    public void refresh() {
        SupplierDAO dao = new SupplierDAO();
        refreshData(dao.getAllSupplier());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSupplier = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblPembelian = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jLabel1.setText("Cari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 18);
        add(jtfSearch, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(jButton2, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblSupplier);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi Pembelian"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblPembelian);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    DialogTambahSupplier d = new DialogTambahSupplier(null, true);
    d.setVisible(true);
    refreshData(new SupplierDAO().getAllSupplier());
}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblPembelian;
    private javax.swing.JTable jtblSupplier;
    private javax.swing.JTextField jtfSearch;
    // End of variables declaration//GEN-END:variables

    public class ButtonEditorListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            DialogUbahSupplier dialog = new DialogUbahSupplier(null, true, Integer.parseInt(btnEditor.getCellEditorValue().toString()));
            dialog.setVisible(true);
            refreshData(new SupplierDAO().getAllSupplier());
        }
    }

    public class DocumentListenerSearchSupplier implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            refreshData(new SupplierDAO().searchSupplier(jtfSearch.getText()));
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            refreshData(new SupplierDAO().searchSupplier(jtfSearch.getText()));
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            refreshData(new SupplierDAO().searchSupplier(jtfSearch.getText()));
        }
    }

    public class PembelianSelectionListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            try {
                NumberFormat numberFormat = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
                SupplierDAO dAO = new SupplierDAO();
                Supplier s = dAO.getSupplierById((Integer) jtblSupplier.getValueAt(jtblSupplier.getSelectedRow(), 0));
                int row = tableModelPembelian.getRowCount();
                for (int i = 0; i < row; i++) {
                    tableModelPembelian.removeRow(0);
                }
                ArrayList<Pembelian> a= new ArrayList<Pembelian>(s.getPembelians());
                Collections.sort(a);
               
                for (Pembelian p:a) {
                    tableModelPembelian.addRow(new Object[]{p.getIdPembelian(), p.getTglBeli(), p.getKurs(), numberFormat.format(p.getHargaTotal())});
                }
            } catch (Exception ex) {
            }

        }
    }
}
