/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogBayarCicilan.java
 *
 * Created on Oct 19, 2011, 8:25:30 PM
 */
package com.prima.view.transaksi;

import com.prima.dao.CicilanDAO;
import com.prima.dao.KreditDAO;
import com.prima.entity.Cicilan;
import com.prima.entity.Kredit;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author raphael
 */
public class DialogBayarCicilan extends javax.swing.JDialog {

    /**
     * Creates new form DialogBayarCicilan
     */
    private int idKredit;
    private NumberFormat formatIDR = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
    private NumberFormat formatUSD = NumberFormat.getCurrencyInstance(Locale.US);
double sisaBayar = 0;
    public DialogBayarCicilan(java.awt.Frame parent, boolean modal, int idKredit) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.idKredit = idKredit;
        init();
    }

    private void init() {
        CicilanDAO cicilanDAO = new CicilanDAO();
        Kredit kredit = new KreditDAO().getKreditById(idKredit);
        jlblIDKredit.setText(kredit.getIdKredit() + "");
        jlblNamaPembeli.setText(kredit.getTransaksi().getPembeli().getNama());
        jlblTglPelunasan.setText(kredit.getTglAkhirPelunasan() + "");
        
        if (kredit.getTransaksi().isMata()) {
            jlblTotalBayar.setText(formatIDR.format(kredit.getTransaksi().getHargaTotal()));
            sisaBayar = kredit.getTransaksi().getHargaTotal() - cicilanDAO.getTotalBayarById(kredit);
            jlblSisaBayar.setText(formatIDR.format(sisaBayar));
        }else{
            jlblTotalBayar.setText(formatUSD.format(kredit.getTransaksi().getHargaTotalUsd()));
            sisaBayar = kredit.getTransaksi().getHargaTotalUsd() - cicilanDAO.getTotalBayarById(kredit);
            jlblSisaBayar.setText(formatUSD.format(sisaBayar));
        }

//        SpinnerNumberModel model = (SpinnerNumberModel) jspJumlahBayar.getModel();
//        model.setMaximum(sisaBayar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblIDKredit = new javax.swing.JLabel();
        jlblNamaPembeli = new javax.swing.JLabel();
        jlblTglPelunasan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblTotalBayar = new javax.swing.JLabel();
        jlblSisaBayar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jrbCash = new javax.swing.JRadioButton();
        jrbGiro = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtfNogiro = new com.prima.view.model.NumberTextbox();
        jtfBayar = new com.prima.view.model.NumberTextbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bayar Cicilan");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID Kredit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nama Pembeli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Tanggal Pelunasan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel3, gridBagConstraints);

        jlblIDKredit.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jlblIDKredit, gridBagConstraints);

        jlblNamaPembeli.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jlblNamaPembeli, gridBagConstraints);

        jlblTglPelunasan.setText("jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jlblTglPelunasan, gridBagConstraints);

        jLabel7.setText("Total Bayar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Sisa Bayar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel8, gridBagConstraints);

        jlblTotalBayar.setText("jLabel9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jlblTotalBayar, gridBagConstraints);

        jlblSisaBayar.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jlblSisaBayar, gridBagConstraints);

        jLabel4.setText("Jumlah Bayar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel4, gridBagConstraints);

        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel5.setText("Jenis Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel5, gridBagConstraints);

        buttonGroup1.add(jrbCash);
        jrbCash.setSelected(true);
        jrbCash.setText("Cash");
        jrbCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCashActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jrbCash, gridBagConstraints);

        buttonGroup1.add(jrbGiro);
        jrbGiro.setText("Giro");
        jrbGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGiroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jrbGiro, gridBagConstraints);

        jLabel6.setText("No Giro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel6, gridBagConstraints);

        jtfNogiro.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jtfNogiro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jtfBayar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    if (Double.parseDouble(jtfBayar.getText()) == 0||Double.parseDouble(jtfBayar.getText())>sisaBayar) {
        JOptionPane.showMessageDialog(this, "Jumlah bayar salah");
    } else {
        String jenis = "Cash";
        CicilanDAO cicilanDAO = new CicilanDAO();
        Cicilan c = new Cicilan();
        Kredit k = new KreditDAO().getKreditById(idKredit);
        c.setKredit(k);
        c.setTglCicilan(new Date());
        c.setJumlahBayar(Double.parseDouble(jtfBayar.getText()));
        c.setNoGiro(jtfNogiro.getText());
        if (jrbGiro.isSelected()) {
            jenis = "Giro";
        }
        c.setJenis(jenis);
        cicilanDAO.save(c);
        CicilanDAO dao = new CicilanDAO();
        double sisaBayar = k.getTransaksi().getHargaTotal() - dao.getTotalBayarById(k);
        if (sisaBayar == 0) {
            Kredit kredit = new Kredit();
            //kredit.setCicilans();
            kredit.setIdKredit(idKredit);
            kredit.setTglAkhirPelunasan(k.getTglAkhirPelunasan());
            kredit.setTransaksi(k.getTransaksi());
            kredit.setStatus(true);
            new KreditDAO().update(kredit);
        }
        this.setVisible(false);
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jrbCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCashActionPerformed
    jtfNogiro.setEnabled(false);
}//GEN-LAST:event_jrbCashActionPerformed

private void jrbGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGiroActionPerformed
    jtfNogiro.setEnabled(true);
}//GEN-LAST:event_jrbGiroActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlblIDKredit;
    private javax.swing.JLabel jlblNamaPembeli;
    private javax.swing.JLabel jlblSisaBayar;
    private javax.swing.JLabel jlblTglPelunasan;
    private javax.swing.JLabel jlblTotalBayar;
    private javax.swing.JRadioButton jrbCash;
    private javax.swing.JRadioButton jrbGiro;
    private com.prima.view.model.NumberTextbox jtfBayar;
    private com.prima.view.model.NumberTextbox jtfNogiro;
    // End of variables declaration//GEN-END:variables
}
