/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTransaksi.java
 *
 * Created on Oct 18, 2011, 9:47:27 AM
 */
package com.prima.view.transaksi;

import java.awt.BorderLayout;

/**
 *
 * @author raphael
 */
public class PanelTransaksi extends javax.swing.JPanel {

    /** Creates new form PanelTransaksi */
    private PanelLihatTransaksi panelLihatTransaksi= new PanelLihatTransaksi();
    private PanelTambahTransaksi panelTambahTransaksi= new PanelTambahTransaksi();
    private PanelPembayaranCicilan panelPembayaranCicilan= new PanelPembayaranCicilan();
    public PanelTransaksi() {
        initComponents();
        jPanel1.add(panelTambahTransaksi,BorderLayout.CENTER);
        jPanel2.add(panelLihatTransaksi,BorderLayout.CENTER);
        jPanel3.add(panelPembayaranCicilan,BorderLayout.CENTER);
    }
    
    public void refresh(){
        panelLihatTransaksi.refresh();
        panelPembayaranCicilan.refresh();
        panelTambahTransaksi.refresh();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Tambah Transaksi", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Lihat Transaksi", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Pembayaran Kredit", jPanel3);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    refresh();
}//GEN-LAST:event_jTabbedPane1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
